service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  lamba-node-api:
    handler: handler.handler
    events:
     - http:
        path: /
        method: get
        cors: true
     - http:
        path: /{proxy+}
        method: any
        cors: true
